// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiY8vBLm5ViWYDje7042KbMImgaLtmphg',
    appId: '1:534045033205:web:b72f827b1edfe937dafbbc',
    messagingSenderId: '534045033205',
    projectId: 'automated-irrigation-sys-4d93e',
    authDomain: 'automated-irrigation-sys-4d93e.firebaseapp.com',
    databaseURL: 'https://automated-irrigation-sys-4d93e-default-rtdb.firebaseio.com',
    storageBucket: 'automated-irrigation-sys-4d93e.appspot.com',
    measurementId: 'G-8MC0Y5ECZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVwK152RR46LB3H5zh6jbqmsG___dh2o',
    appId: '1:534045033205:android:0037cdaf092b0d73dafbbc',
    messagingSenderId: '534045033205',
    projectId: 'automated-irrigation-sys-4d93e',
    databaseURL: 'https://automated-irrigation-sys-4d93e-default-rtdb.firebaseio.com',
    storageBucket: 'automated-irrigation-sys-4d93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGNIMEzYllzZMX3x9qu4_TGDueLsgF8U',
    appId: '1:534045033205:ios:5fb54f4f52aad84fdafbbc',
    messagingSenderId: '534045033205',
    projectId: 'automated-irrigation-sys-4d93e',
    databaseURL: 'https://automated-irrigation-sys-4d93e-default-rtdb.firebaseio.com',
    storageBucket: 'automated-irrigation-sys-4d93e.appspot.com',
    iosClientId: '534045033205-uq68dt203417b53it0842393721nct0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartIrrigationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGNIMEzYllzZMX3x9qu4_TGDueLsgF8U',
    appId: '1:534045033205:ios:5fb54f4f52aad84fdafbbc',
    messagingSenderId: '534045033205',
    projectId: 'automated-irrigation-sys-4d93e',
    databaseURL: 'https://automated-irrigation-sys-4d93e-default-rtdb.firebaseio.com',
    storageBucket: 'automated-irrigation-sys-4d93e.appspot.com',
    iosClientId: '534045033205-uq68dt203417b53it0842393721nct0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartIrrigationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiY8vBLm5ViWYDje7042KbMImgaLtmphg',
    appId: '1:534045033205:web:0d06db373562673ddafbbc',
    messagingSenderId: '534045033205',
    projectId: 'automated-irrigation-sys-4d93e',
    authDomain: 'automated-irrigation-sys-4d93e.firebaseapp.com',
    databaseURL: 'https://automated-irrigation-sys-4d93e-default-rtdb.firebaseio.com',
    storageBucket: 'automated-irrigation-sys-4d93e.appspot.com',
    measurementId: 'G-1NR1N8FD7W',
  );

}